In [1]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Arrays

In [2]:
import numpy as np
oneD=np.array([1,2,3,4,5])
print("array:", oneD)
print("shape:", oneD.shape)

array: [1 2 3 4 5]
shape: (5,)


In [3]:
twoD=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array:\n",twoD)
print("shape:", twoD.shape)

array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)


In [4]:
threeD=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("array:\n",threeD)
print("shape:",threeD.shape)

array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


List,tuples in Arrays

In [5]:
list_data=[1,2,3,4,5]
array_frm_lst=np.array(list_data)
print(array_frm_lst)

[1 2 3 4 5]


In [7]:
tuple_data=(1,2,3,4,5)
array_frm_tpl=np.array(tuple_data)
print(array_frm_tpl)


[1 2 3 4 5]


In [6]:
source_array=np.array([1,2,3,4,5])
#creates seprate copy
new_array=np.array(source_array) 
print(new_array)

# .copy() method to explicitly copy an array
copy_array=source_array.copy()
print("Using copy method:", copy_array)

[1 2 3 4 5]
Using copy method: [1 2 3 4 5]


In [8]:
range_array=np.arange(1,15,5) #(start,upto,step)
print(range_array)

[ 1  6 11]


In [ ]:
linspace_array=np.linspace(1,6,5) # 5 values between 1 and 5
print(linspace_array)

[1.   2.25 3.5  4.75 6.  ]


In [11]:
random_array=np.random.rand(3,3) 
#rand generate float-point numbers
print(random_array)

random_array=np.random.randint(0,5,(3,3))
print("integer Randon Array", random_array)

[[0.83877484 0.39805731 0.64760125]
 [0.42674609 0.97287529 0.53617223]
 [0.61105753 0.39749962 0.47545539]]
integer Randon Array [[0 3 3]
 [3 0 0]
 [2 2 1]]


In [12]:
#np.zeros(shape)
#np.ones(shape)
#np.eye(size)
# np.zeros() and np.ones() expects the shape as a tuple (3,3), not separate arguments
zero_array=np.zeros((3,3))
print("Zeros Array:",zero_array)
one_array=np.ones((2,5))
print("Ones Array:",one_array)
identity_matrix=np.eye(3)
print("Identity Matrix:",identity_matrix)

Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity Matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Indexing & Slicing

In [13]:
# 1D array indexing
array=np.array([1,2,3,4,5])
print(array[0]) # 1st element
print(array[2]) # 3rd element
print(array[-1]) # last element

1
3
5


In [14]:
twoDarray=np.random.randint(1,3,(3,3))
print("2d matrix:", array)
print(twoDarray[0])
print(twoDarray[1,2]) # element at row index 1, column index 2
print(twoDarray[0,0]) # 1st element
print(twoDarray[-1,-1]) # last element

2d matrix: [1 2 3 4 5]
[1 2 2]
1
1
1


In [15]:
threeDarray = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])
print(threeDarray.shape)
print(threeDarray[0,1,2]) # 1st dept, 2nd row, 3rd column

(2, 2, 3)
6


In [16]:
#1D array slicing
array=np.array([1,2,3,4,5])
print(array[1:4]) # elements from index 1 to 3
print(array[:3]) # upto 2
print(array[3:])# from 3 to end
print(array[::2])# every 2nd element
print(array[::-1])# reverse

[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]


In [17]:
#2D array slicing -- slice rows & columns seperately
twoarray=np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(twoarray[:2,1:])# first 2 rows, column from index 1 onwards
print(twoarray[:,0]) # first column
print(twoarray[0,:])# first row
print(twoarray[::-1,::-1]) # reverse the matrix
print(twoarray[::-1,])#reverse the row
print(twoarray[:,::-1])#reverse the column

[[2 3]
 [5 6]]
[1 4 7]
[1 2 3]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [18]:
threeDarray=np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                      [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
print(threeDarray)
print(threeDarray[0,1,:])#1st depth, 2nd row, all column
print(threeDarray[:1,:,:])#frist depth, all rows, all columns
print(threeDarray[:,0:2,1:3])#both depth, 1st and 2nd row, 2nd and 3rd column

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[4 5 6]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[ 2  3]
  [ 5  6]]

 [[11 12]
  [14 15]]]


In [19]:
arr=np.array([1,2,3,4,5])
print(arr[arr>2]) 

[3 4 5]


In [ ]:
Arthematic Operations

In [20]:
#using direct operation
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])

print(a+b)
print(b-a)
print(a*b)
print(a/b)

# Scalar Operations
print(a+5)
print(a*5)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[ 6  7  8  9 10]
[ 5 10 15 20 25]


In [21]:
#using function
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
c=np.add(a,b)
print(c)

[11 22 33 44 55]


In [22]:
print(a**2) #square each element
print(a%3) #Modulus operation
print(a//3) #floor division 

[ 1  4  9 16 25]
[1 2 0 1 2]
[0 0 1 1 1]


In [23]:
print(np.sum(a)) # sum of all elements
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))

15
3.0
3.0
1
5


In [24]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(matrix, axis=0)) # sum of all columns
print(np.sum(matrix, axis=1)) # sum of all rows

[12 15 18]
[ 6 15 24]


In [25]:
#same size arrays
array=np.array([[1,2,3],[4,5,6]])
print(array+10) # adds 10 to each element

[[11 12 13]
 [14 15 16]]


In [26]:
arr1=np.array([[1],[2],[3]]) #shape(3,1)
arr2=np.array([10,20,30]) #shape(3,)
print(arr1+arr2)
# The broadcasting rules are:
# 1.If the two arrays have different dimensions, NumPy automatically expands the smaller array’s shape.
#2.If a dimension has size 1, NumPy duplicates its values along that dimension to match the larger array.

[[11 21 31]
 [12 22 32]
 [13 23 33]]


Array Sahpe Change

In [27]:
#reshape()--function allows us to change the shape of an array without modifying its data
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Convert from (6,) to (2,3)
print(reshaped_arr)
arr = arr.reshape(3, -1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
# ravel() - Flatteninf an array
# Converts a multi-dimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened = arr.ravel()
print(flattened)

[1 2 3 4 5 6]


In [30]:
# transpose() – Swap Axes of an Array
transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
# swapaxes() – Swap Any Two Axes
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape (2,2,2)
print(arr)
swapped = arr.swapaxes(0, 1)
print(swapped)
print(swapped.shape)  # (2,2,2) → (2,2,2) (axes 0 & 1 swapped)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
(2, 2, 2)


In [32]:
# resize() – Change Size with Possible Data Loss
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((2, 4))  # Expands the shape, fills extra values with 0
print(arr)

[[1 2 3 4]
 [5 6 0 0]]


In [33]:
# expand_dims() – Add an Extra Dimension
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)  # Convert (3,) → (1, 3)
print(expanded.shape)  # Output: (1,3)

(1, 3)


In [34]:
# squeeze() – Remove Extra Dimensions
arr = np.array([[[1, 2, 3]]])  # Shape (1,1,3)
squeezed = arr.squeeze()
print(squeezed.shape) 

(3,)


In [35]:
# concatenate() – Join Arrays Along an Axis
a = np.array([[1, 2]])
b = np.array([[5, 6]])
Colcon = np.concatenate((a, b), axis=1)
print(Colcon)
rowcon = np.concatenate((a, b), axis=0)
print(rowcon)

[[1 2 5 6]]
[[1 2]
 [5 6]]
